# Generated by Django 5.2.4 on 2025-07-15 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='is_from_admin',
            field=models.BooleanField(default=False),
        ),
    ]
