# Generated by Django 5.2.4 on 2025-07-16 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_usermodel_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='is_chatbanned',
            field=models.BooleanField(default=False),
        ),
    ]
