# Generated by Django 5.2.4 on 2025-07-17 18:20

import accounts.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_address_account_alter_address_address_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[accounts.validators.PhoneNumberValidator()]),
        ),
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(blank=True, max_length=50, null=True, validators=[accounts.validators.NoProfanityValidator()]),
        ),
        migrations.AlterField(
            model_name='address',
            name='country',
            field=models.CharField(blank=True, max_length=50, null=True, validators=[accounts.validators.NoProfanityValidator()]),
        ),
        migrations.AlterField(
            model_name='address',
            name='label',
            field=models.CharField(blank=True, max_length=30, null=True, validators=[accounts.validators.NoProfanityValidator()]),
        ),
        migrations.AlterField(
            model_name='address',
            name='state',
            field=models.CharField(blank=True, max_length=50, null=True, validators=[accounts.validators.NoProfanityValidator()]),
        ),
        migrations.AlterField(
            model_name='address',
            name='street_address',
            field=models.CharField(blank=True, max_length=100, null=True, validators=[accounts.validators.NoProfanityValidator()]),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='username',
            field=models.CharField(max_length=150, unique=True, validators=[accounts.validators.NoProfanityValidator()]),
        ),
    ]
