# Generated by Django 5.2.4 on 2025-07-19 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_account_first_name_account_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='country_code',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
