# Generated by Django 5.2.4 on 2025-07-25 07:11

import accounts.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_remove_account_default_billing_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='postal_code',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[accounts.validators.PostalCodeValidator(max_length=10, min_length=4)]),
        ),
    ]
