# Generated by Django 5.2.4 on 2025-07-27 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_alter_account_first_name_alter_account_last_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='label',
        ),
    ]
