# Generated by Django 5.2.4 on 2025-08-04 19:52

import accounts.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_usermodel_username_alter_usermodel_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='username',
            field=models.CharField(max_length=150, unique=True, validators=[accounts.validators.NoProfanityValidator()]),
        ),
    ]
