# Generated by Django 5.2.4 on 2025-07-17 18:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='rating',
            field=models.PositiveIntegerField(default=5, validators=[django.core.validators.MaxValueValidator(5)]),
            preserve_default=False,
        ),
    ]
