# Generated by Django 5.2.4 on 2025-07-22 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_remove_product_rating_rating'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tag',
        ),
        migrations.RemoveField(
            model_name='product',
            name='tags',
        ),
    ]
