# Generated by Django 5.2.4 on 2025-07-24 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_delete_tag_remove_product_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='quantity',
        ),
    ]
